# wrangler.toml - AI YouTube Playlist Curator
# Updated for Phase 3: AI Enhancement Engine

name = "playlist-ai"
main = "src/workers/api-worker.js"
compatibility_date = "2024-03-01"

# Environment variables for local development only
[vars]
ENVIRONMENT = "development"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "playlist-ai-db"
database_id = "702d7210-6ee3-4462-9101-a41a3877068b"

# KV namespace for sessions and caching
[[kv_namespaces]]
binding = "SESSIONS"
id = "d08b2f068c944da1ace819d9441bee68"

# Additional KV namespace for caching (can use same as SESSIONS)
[[kv_namespaces]]
binding = "CACHE"
id = "d08b2f068c944da1ace819d9441bee68"

# Development environment
[env.development]
[env.development.vars]
ENVIRONMENT = "development"
JWT_SECRET = "local-dev-jwt-secret-key-minimum-32-characters-for-testing-purposes-only"
# For local testing, uncomment and add your API keys:
# YOUTUBE_API_KEY = "your-youtube-api-key-here"
# OPENAI_API_KEY = "your-openai-api-key-here"

# Staging environment
[env.staging]
name = "playlist-ai-staging"
[env.staging.vars]
ENVIRONMENT = "staging"

[[env.staging.d1_databases]]
binding = "DB"
database_name = "playlist-ai-db-staging"
database_id = "your-staging-d1-id"

[[env.staging.kv_namespaces]]
binding = "SESSIONS"
id = "your-staging-kv-id"

[[env.staging.kv_namespaces]]
binding = "CACHE"
id = "your-staging-cache-kv-id"

# Production environment
[env.production]
name = "playlist-ai-production"
[env.production.vars]
ENVIRONMENT = "production"

[[env.production.d1_databases]]
binding = "DB"
database_name = "playlist-ai-db-production"
database_id = "your-production-d1-id"

[[env.production.kv_namespaces]]
binding = "SESSIONS"
id = "your-production-kv-id"

[[env.production.kv_namespaces]]
binding = "CACHE"
id = "your-production-cache-kv-id"

# Analytics and observability
[observability]
enabled = true

# IMPORTANT: Set up secrets for production using:
# wrangler secret put JWT_SECRET
# wrangler secret put YOUTUBE_API_KEY (for Phase 2 features)
# wrangler secret put OPENAI_API_KEY (for Phase 3 AI features)