# wrangler.toml - Fixed with local development secret support

name = "playlist-ai"
main = "src/workers/api-worker.js"
compatibility_date = "2024-03-01"

# Environment variables for local development only
[vars]
ENVIRONMENT = "development"
# Note: JWT_SECRET removed for production security - use wrangler secret put instead

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "playlist-ai-db"
database_id = "702d7210-6ee3-4462-9101-a41a3877068b"

# KV namespace for sessions
[[kv_namespaces]]
binding = "SESSIONS"
id = "d08b2f068c944da1ace819d9441bee68"

# Development settings
[env.development]
[env.development.vars]
ENVIRONMENT = "development"
JWT_SECRET = "local-dev-jwt-secret-key-minimum-32-characters-for-testing-purposes-only"

# Staging environment (uses actual secrets)
[env.staging]
name = "playlist-ai-staging"
[env.staging.vars]
ENVIRONMENT = "staging"
# Note: JWT_SECRET will come from wrangler secret put in staging/production

[[env.staging.d1_databases]]
binding = "DB"
database_name = "playlist-ai-db-staging"
database_id = "your-staging-d1-id"

[[env.staging.kv_namespaces]]
binding = "SESSIONS"
id = "your-staging-kv-id"

# Production environment (uses actual secrets)
[env.production]
name = "playlist-ai-production"
[env.production.vars]
ENVIRONMENT = "production"
# Note: JWT_SECRET will come from wrangler secret put in production

[[env.production.d1_databases]]
binding = "DB"
database_name = "playlist-ai-db-production"
database_id = "your-production-d1-id"

[[env.production.kv_namespaces]]
binding = "SESSIONS"
id = "your-production-kv-id"

# Analytics and observability
[observability]
enabled = true

# Note: CPU limits removed - not supported on Free plan
# [limits]
# cpu_ms = 50